"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./point");
var triangle_1 = require("./triangle");
var vertex1 = new point_1.Point(7, 3);
var vertex2 = new point_1.Point(3, 3);
var vertex3 = new point_1.Point(7, 4);
var triangulo = new triangle_1.Triangle(vertex1, vertex2, vertex3);
var lados = triangulo.calculateLengthSides();
console.log(lados);
